/**
 * Default option values for KatuCharts.
 */

import type { KatuChartsOptions } from '../types/options';
import { DEFAULT_COLORS } from '../utils/color';
import { DEFAULT_CHART_TEXT_COLOR, DEFAULT_CHART_TEXT_SIZE } from '../utils/chartText';

export const defaultOptions: KatuChartsOptions = {
  chart: {
    type: 'line',
    backgroundColor: '#ffffff',
    borderWidth: 0,
    borderRadius: 0,
    borderColor: '#335cad',
    spacing: [10, 10, 15, 10],
    style: { fontFamily: '"Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif', fontSize: '12px' },
    animation: true,
    zoomType: undefined,
    panning: false,
    inverted: false,
    polar: false,
    reflow: true,
  },
  title: {
    text: undefined,
    align: 'center',
    margin: 15,
    style: { color: '#333333', fontSize: '18px', fontWeight: 'bold' },
    widthAdjust: -44,
  },
  subtitle: {
    text: undefined,
    align: 'center',
    style: { color: '#666666', fontSize: '12px' },
    widthAdjust: -44,
  },
  xAxis: {
    type: 'linear',
    title: { text: null, style: { color: DEFAULT_CHART_TEXT_COLOR, fontSize: DEFAULT_CHART_TEXT_SIZE } },
    labels: {
      enabled: true,
      style: { color: DEFAULT_CHART_TEXT_COLOR, fontSize: DEFAULT_CHART_TEXT_SIZE },
      autoRotation: [-45],
      autoRotationLimit: 80,
      padding: 5,
    },
    tickLength: 10,
    tickWidth: 1,
    tickColor: '#ccd6eb',
    gridLineWidth: 0,
    gridLineColor: '#e6e6e6',
    lineWidth: 1,
    lineColor: '#ccd6eb',
    offset: 0,
    opposite: false,
    reversed: false,
    visible: true,
    startOnTick: false,
    endOnTick: false,
    showFirstLabel: true,
    showLastLabel: true,
    allowDecimals: true,
    maxPadding: 0.01,
    minPadding: 0.01,
    crosshair: false,
  },
  yAxis: {
    type: 'linear',
    title: { text: 'Values', style: { color: DEFAULT_CHART_TEXT_COLOR, fontSize: DEFAULT_CHART_TEXT_SIZE } },
    labels: {
      enabled: true,
      style: { color: DEFAULT_CHART_TEXT_COLOR, fontSize: DEFAULT_CHART_TEXT_SIZE },
      padding: 5,
    },
    tickLength: 0,
    tickWidth: 0,
    gridLineWidth: 1,
    gridLineColor: '#e6e6e6',
    lineWidth: 0,
    lineColor: '#ccd6eb',
    offset: 0,
    opposite: false,
    reversed: false,
    visible: true,
    startOnTick: true,
    endOnTick: true,
    showFirstLabel: true,
    showLastLabel: true,
    allowDecimals: true,
    maxPadding: 0.05,
    minPadding: 0.05,
    crosshair: false,
  },
  colorAxis: undefined,
  series: [],
  tooltip: {
    enabled: true,
    shared: false,
    split: false,
    useHTML: false,
    followPointer: false,
    headerFormat: '<span style="font-size: 10px">{point.key}</span><br/>',
    pointFormat: '<span style="color:{point.color}">\u25CF</span> {series.name}: <b>{point.y}</b><br/>',
    footerFormat: '',
    backgroundColor: 'rgba(247,247,247,0.85)',
    borderColor: undefined,
    borderWidth: 1,
    borderRadius: 3,
    padding: 8,
    shadow: true,
    animation: true,
    hideDelay: 500,
    snap: 10,
    outside: false,
    style: { color: '#333333', fontSize: '12px' },
  },
  legend: {
    enabled: true,
    layout: 'horizontal',
    align: 'center',
    verticalAlign: 'bottom',
    floating: false,
    x: 0,
    y: 0,
    margin: 15,
    padding: 8,
    itemMarginTop: 0,
    itemMarginBottom: 0,
    itemDistance: 20,
    itemStyle: { color: DEFAULT_CHART_TEXT_COLOR, cursor: 'pointer', fontSize: DEFAULT_CHART_TEXT_SIZE, fontWeight: 'normal' },
    itemHoverStyle: { color: '#000000' },
    itemHiddenStyle: { color: '#cccccc' },
    symbolWidth: 12,
    symbolHeight: 12,
    symbolRadius: 2,
    symbolPadding: 5,
    squareSymbol: true,
    borderWidth: 0,
    borderRadius: 0,
    borderColor: '#999999',
    reversed: false,
  },
  plotOptions: {
    series: {
      lineWidth: 2,
      marker: {
        enabled: null,
        radius: 4,
        symbol: 'circle',
        lineWidth: 0,
        states: {
          hover: { enabled: true, radius: 6, lineWidth: 1 },
        },
      },
      states: {
        hover: { enabled: true, lineWidthPlus: 1 },
        inactive: { opacity: 0.2 },
      },
      animation: { duration: 1000 },
      enableMouseTracking: true,
      stickyTracking: true,
      allowPointSelect: false,
      turboThreshold: 1000,
      dataLabels: { enabled: false },
      showInLegend: true,
      threshold: 0,
      connectNulls: false,
      clip: true,
    },
    bubble: {
      lineWidth: 1,
    },
    scatter: {
      marker: { symbol: null },
    },
    pie: {
      tooltip: {
        pointFormat: '<span style="color:{point.color}">\u25CF</span> {series.name}: <b>{point.percentage:.1f}%</b><br/>',
      },
      dataLabels: { enabled: true },
      showInLegend: false,
    },
    donut: {
      showInLegend: false,
    },
    sankey: { dataLabels: { enabled: true } },
    dependencywheel: { dataLabels: { enabled: true } },
    networkgraph: { dataLabels: { enabled: true } },
    treemap: { dataLabels: { enabled: true } },
    gauge: { dataLabels: { enabled: true } },
    solidgauge: { dataLabels: { enabled: true } },
    timeline: { dataLabels: { enabled: true } },
    gantt: { dataLabels: { enabled: true } },
    barchartrace: { dataLabels: { enabled: true } },
    venn: { dataLabels: { enabled: true } },
  },
  credits: {
    enabled: true,
    text: 'Powered by: KatuCharts',
    href: 'https://charts.katudv.com',
    position: { align: 'right', verticalAlign: 'bottom', x: -10, y: -5 },
    style: { cursor: 'pointer', color: '#999999', fontSize: '9px' },
  },
  exporting: {
    enabled: true,
    filename: 'chart',
    type: 'image/png',
    scale: 2,
    printMaxWidth: 780,
    buttons: {
      contextButton: {
        enabled: true,
        symbol: 'gear',
        symbolFill: '#666666',
        symbolStroke: '#666666',
        symbolStrokeWidth: 3,
        x: -10,
        y: 10,
        menuItems: ['downloadPNG', 'downloadJPEG', 'downloadSVG', 'downloadPDF', 'separator', 'viewFullScreen', 'printChart'],
      },
    },
  },
  loading: {
    hideDuration: 100,
    showDuration: 100,
    labelStyle: { fontWeight: 'bold', position: 'relative', top: '45%' },
    style: { position: 'absolute', backgroundColor: '#ffffff', opacity: 0.5, textAlign: 'center' },
  },
  navigator: { enabled: false },
  rangeSelector: { enabled: false },
  drilldown: { animation: true, series: [] },
  responsive: {
    rules: [
      {
        condition: { maxWidth: 500 },
        chartOptions: {
          chart: { spacing: [5, 5, 10, 5] },
          title: { style: { fontSize: '14px' }, margin: 8 },
          subtitle: { style: { fontSize: '10px' } },
          legend: {
            itemStyle: { fontSize: '10px' },
            itemDistance: 10,
            margin: 8,
            symbolWidth: 12,
            symbolHeight: 8,
          },
          yAxis: {
            title: { text: null },
            labels: { style: { fontSize: '9px' } },
          },
          xAxis: {
            labels: { style: { fontSize: '9px' }, autoRotation: [-45, -90] },
          },
          plotOptions: {
            pie: {
              size: '65%',
              dataLabels: {
                distance: 10,
                style: { fontSize: '9px' },
                connectorPadding: 3,
              },
            },
          },
        },
      },
      {
        condition: { maxWidth: 350 },
        chartOptions: {
          subtitle: { text: null },
          legend: { enabled: false },
          credits: { enabled: false },
          plotOptions: {
            pie: {
              size: '55%',
              dataLabels: {
                distance: 5,
                style: { fontSize: '8px' },
                connectorWidth: 0,
              },
            },
          },
        },
      },
    ],
  },
  accessibility: { enabled: true },
  colors: DEFAULT_COLORS,
};
